models:
  - name: gpt-4o
    temperature: 0.1
    max_tokens: 2000
    repeat: 1
  - name: deepseek-chat
    temperature: 0.1
    max_tokens: 2000
    repeat: 1
  - name: claude-opus-4-20250514
    temperature: 0.1
    max_tokens: 2000
    repeat: 1
  - name: gemini-2.5-pro
    temperature: 0.1
    max_tokens: 4000
    repeat: 1
